version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - flask_mongo

  flask_mongo:
    build:
      context: .
      dockerfile: ./flask_mongodb/Dockerfile
    volumes:
      - ./flask_mongodb:/flask_mongodb
    ports:
      - "5001:5001"
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: